### ISSUE TITLE
Default code highlighting in Markdown

### ISSUE THREAD

**Issue by rmorabia** [alexanderbast/vscode-snazzy#3]
When there is no specified language for a code block, the colors default to white. This should be changed to a bright block of a different color. Screenshot included. 

![screenshot from 2017-12-26 20 14 51](https://user-images.githubusercontent.com/3877076/34370511-73fa9f40-ea79-11e7-9b80-4abbd57ad756.png)

**Comment by instaatze** [comment]
Thanks for the request!
This is part of update [v2.9.0](https://github.com/alexanderbast/vscode-snazzy/releases/tag/v2.9.0).

**Comment by rmorabia** [comment]
Cool, thank you!
